flashcards/cards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        "",
        views.CardListViews.as_view(),
        name="card-list"),
    path(
        "novo",
        views.CardCreateView.as_view(),
        name="card-create"),
    path(
        "editar/<int:pk>",
        views.CardUpdateView.as_view(),
        name="card-update"
    ),
    path(
        "caixa/<int:num_caixa>",
        views.Caixas.as_view(),
        name="caixa"
    ),
]

flashcards/flashcards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("cards.urls")),
]

flashcards/cards/models.py
from django.db import models

NUM_CAIXAS = 5
CAIXAS = range(1, NUM_CAIXAS + 1)

class Card(models.Model):
    """
    Esta class representa o modelo dos cartões.
    """
    questao  = models.CharField(max_length=140)
    resposta  = models.CharField(max_length=140)
    caixa = models.IntegerField(
        choices=zip(CAIXAS, CAIXAS),
        default=CAIXAS[0],
    )
    data_de_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.questao

    def mover_cartao(self, resposta):
        nova_caixa = self.caixa + 1 if resposta else CAIXAS[0]

        if nova_caixa in CAIXAS:
            self.caixa = nova_caixa
            self.save()

        return self

flashcards/cards/forms.py
from django import forms

class CheckForm(forms.Form):
    id_do_cartao = forms.IntegerField(required=True)
    resposta = forms.BooleanField(required=False)

flashcards/cards/views.py
import random

from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic import(
    ListView,
    CreateView,
    UpdateView,
)
from django.shortcuts import get_object_or_404, redirect
from .forms import CheckForm

from .models import Card


class CardListViews(ListView):
    """ 
    Classe Genêrica para listar todos os cartões
    """
    model = Card
    queryset = Card.objects.all().order_by("caixa", "-data_de_criacao")

class CardCreateView(CreateView):
    """
    Classe genêrica para criar os cartões.
    """
    model = Card
    fields = ["questao", "resposta", "caixa"]
    seccess_url = reverse_lazy("card-create")

class CardUpdateView(CardCreateView, UpdateView):
    """
    Class genêrica para editar os cartões.
    
    Parar editar os cartões, está class 
    extende, os atributos da class CardCreateView
    mudando apenas a URL de sucesso
    """
    success_url = reverse_lazy("card-list")

class Caixas(CardListViews):
    """
    Esta class mostra o conteudo de uma caixa.
    
    Em vez de listar todos os devolve os cartões 
    onde o número da caixa cartões corresponde ao 
    num_caixa.
    """
    
    templates = "cards/caixa.html"
    form_class = CheckForm

    def get_queryset(self):
        return Card.objects.filter(caixa=self.kwargs["num_caixa"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_da_caixa"] = self.kwargs["num_caixa"]
        if self.object_list:
            context["check_card"] = random.choice(self.object_list)
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            card = get_object_or_404(Card, id=form.cleaned_data["id_do_cartao"])
            card. mover_cartao(form.cleaned_data["resposta"])

        return redirect(request.META.get("HTTP_REFERER"))

flashcards/cards/templates/cards/base.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flashcards</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/w3.css' %}">
</head>
<style>
    /* Custom CSS */

    :root {
        --accent: #6e48ad;
        --accent-bg: white;
        --bg: #fff;
        --text: #212121;
        --text-light: #585858;
        --border: #d8dae1;
        --code: #d81b60;
        --preformatted: #444;
    }

    article {
        background-color: var(--marked);
        border: 1px solid var(--border);
        border-radius: 5px;
        padding: 1em;
        margin: 1em 0;
    }

    h2 {
        text-align: center;
    }

    h2, h4 {
        margin-top: 0;
    }

    hr {
        background: var(--accent);
        border-color: var(--accent);
    }

    button,
    a[role="button"] {
        color: white;
        text-decoration: none;
    }
    a{
        text-decoration: none;
    }

    input, select, textarea {
        width: 100%;
    }
    #id_questao, #id_resposta, #id_caixa{
        border: 1px solid gray;
        border-radius: 3px;
        padding: 9px;
    }
</style>

<body>
    <header class="w3-padding-large w3-blue">
        <h1>
            <a href="{% url 'card-list' %}" class="w3-hover-text-white">Flashcards app</a>
        </h1>
        {% include "cards/navigation.html" %}
    </header>
    <main  style="max-width: 60%; margin:16px auto;">
        {% block content%}
            <h2>Bem Vindo ao Flashcards !!</h2>
        {% endblock %}
    </main>    
</body>

</html>

flashcards/cards/templates/cards/box_links.html
{% load humanize %}

{% for box in caixas %}
    <a href="{% url 'caixa' num_caixa=box.numero %}" 
        class="w3-padding w3-hover-text-yellow">
        🗃 {{ box.numero | ordinal }} Caixa  <mark>{{ box.card_count }}</mark>
    </a>
{% endfor %}

flashcards/cards/templates/cards/caixa.html
{% extends "cards/base.html" %}
{% load humanize %}

{% block content %}
	<h2>{{ num_da_caixa | ordinal }} Caixa</h2>
	<mark>{{ object_list | length }} Cartão{{object_list | pluralize}} a esquerda</mark>
	<hr>
	{% if check_card %}
		{% include "cards/card.html" with cartao=check_card %}
	{% endif %}
{% endblock %}

flashcards/cards/templates/cards/card.html
<!-- Representação dos cartões -->
<article>
    <h4>{{cartao.questao}}</h4>
    {% if not check_card %}
        <p>{{ cartao.resposta }}</p>
        <hr>
        <a href="{% url 'card-update' cartao.id %}">
            ✏️ Editar Cartão
        </a>
    {% else %}
       <details>
           <summary>Revelar Resposta</summary>
           <p>{{ cartao.resposta }}</p>
       </details>
       <hr>
       {% include "cards/card_check_form.html" with resposta=True %}
       {% include "cards/card_check_form.html" with resposta=False %}
    {% endif %}
</article>

flashcards/cards/templates/cards/card_check_form.html
<form method="post">
    {% csrf_token %}

    <input type="hidden" name="id_do_cartao" value="{{ cartao.id }}">
    <input type="hidden" name="resposta" value="{{ resposta }}">
    {% if resposta %}
        <input type="submit" value="✅ Eu sei!" style="width: 25%;" class="w3-padding w3-margin-bottom" />
    {% else %}
        <input type="submit" value="❌ Não sei." style="width: 25%;" class="w3-padding" />
    {% endif %}
</form>

flashcards/cards/templates/cards/card_form.html
{% extends "cards/base.html" %}

{% block content %}
    {% if card %}
        <h2>✏️ Editar cartão</h2>
    {% else %}
        <h2>✨ Criar novo cartão !</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Salvar Cartão" class="w3-btn ">
    </form>
    <a href="{% url 'card-list' %}" class="w3-btn w3-red w3-padding w3-margin-top">
        Cancelar
    </a>
{% endblock %}

flashcards/cards/templates/cards/card_list.html
{% extends "cards/base.html" %}
{% load humanize %}

{% block content %}
    <h2>Lista de cartões</h2>

    <a href="{%url  'card-create' %}" 
        class="w3-blue w3-padding w3-margin-buttom" role="button">
        Criar Novo cratão
    
    </a>

    {% for cartao in card_list %}
        {% ifchanged %}
            <h3>🗃 {{ cartao.caixa | ordinal }} Caixa </h3>
        {% endifchanged %}
        {% include "cards/card.html" %}
    {% endfor %}

{% endblock %}

flashcards/cards/templates/cards/navigation.html
{% load cards_tags %}

<nav class="w3-center w3-large">
    {% link_das_caixas %}
</nav>